### PR TITLE
Removed small pngs and uploaded svgs

### PR DESCRIPTION
**Pull request by Subtenko**
Got svgs up, a few may have an early cut on the bottom but we can re-edit it later if necessary.

### CODE REVIEW

**Comment by kkaja123** [comment]
The quality looks good. What's with some of the images getting cut off at the bottom? For example, the elastic icon and the bolt icon both have flat bottoms from being cut off.

Edit: oops, I saw your comment just after posting my comment. So you are aware of some getting cut off. We can use them for now. Why are some cut off though?

**Comment by Subtenko** [comment]
> 
> 
> The quality looks good. What's with some of the images getting cut off at the bottom? For example, the elastic icon and the bolt icon both have flat bottoms from being cut off.
> 
> Edit: oops, I saw your comment just after posting my comment. So you are aware of some getting cut off. We can use them for now. Why are some cut off though?

thats how they were from the icon grab (which was the quickest process imo). Its not that many thankfully and they are all within the boundary of your calculator icon.

Do we need to make pngs from it to or can svgs work fine?

**Comment by kkaja123** [comment]
I _think_ SVGs will be fine. I couldn't get SVGs to stretch from JavaScript, so I need PNGs when the image needs to stretch. Since the icons should never be stretched, SVGs should be good. Square scaling (i.e. zooming in and out) works fine with SVGs last I checked. I will double check that after I integrate the new icons into the script.

**Comment by Subtenko** [comment]
> 
> 
> I _think_ SVGs will be fine. I couldn't get SVGs to stretch from JavaScript, so I need PNGs when the image needs to stretch. Since the icons should never be stretched, SVGs should be good. Square scaling (i.e. zooming in and out) works fine with SVGs last I checked. I will double check that after I integrate the new icons into the script.

Alright, after I finish some more community stuff Ima try out some tooltip or popup menu stuff. What do you think about the folder structure? I left mine as is, but I see you made some. If you need to move it to the other folder if it works out better then I guess I'll find out if/when.

**Comment by kkaja123** [comment]
I might change it around to make it a bit more straightforward.

**Pull request merged**
